package com.nikolaevskii.lyte.core.design.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val LyteLightColorScheme = lightColorScheme(
    primary = Color(0xFF245C00),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCDF593),
    onPrimaryContainer = Color(0xFF051F00),
    secondary = Color(0xFFA13018),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDAD2),
    onSecondaryContainer = Color(0xFF3A0904),
    tertiary = Color(0xFF4B4FAB),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE0DEFF),
    onTertiaryContainer = Color(0xFF12134A),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFFBFDF4),
    onBackground = Color(0xFF1A1C18),
    surface = Color(0xFFFBFDF4),
    onSurface = Color(0xFF1A1C18),
    surfaceVariant = Color(0xFFE0E5D3),
    onSurfaceVariant = Color(0xFF43483C),
    surfaceDim = Color(0xFFDADCD1),
    surfaceBright = Color(0xFFFBFDF4),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF4F6EA),
    surfaceContainer = Color(0xFFEEF1E4),
    surfaceContainerHigh = Color(0xFFE8EBDE),
    surfaceContainerHighest = Color(0xFFE2E5D8),
    outline = Color(0xFF74796B),
    outlineVariant = Color(0xFFC4C9B8),
    inverseSurface = Color(0xFF2E312C),
    inverseOnSurface = Color(0xFFEFF2E6),
    inversePrimary = Color(0xFFA6D768),
    scrim = Color(0xFF000000),
)

internal val LyteDarkColorScheme = darkColorScheme(
    primary = Color(0xFFA6D768),
    onPrimary = Color(0xFF0E3300),
    primaryContainer = Color(0xFF184700),
    onPrimaryContainer = Color(0xFFCDF593),
    secondary = Color(0xFFFFB19D),
    onSecondary = Color(0xFF5C150A),
    secondaryContainer = Color(0xFF7F2210),
    onSecondaryContainer = Color(0xFFFFDAD2),
    tertiary = Color(0xFFBCBDFF),
    onTertiary = Color(0xFF23266F),
    tertiaryContainer = Color(0xFF363A8C),
    onTertiaryContainer = Color(0xFFE0DEFF),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF12140F),
    onBackground = Color(0xFFE1E4D9),
    surface = Color(0xFF12140F),
    onSurface = Color(0xFFE1E4D9),
    surfaceVariant = Color(0xFF43483C),
    onSurfaceVariant = Color(0xFFC4C9B8),
    surfaceDim = Color(0xFF12140F),
    surfaceBright = Color(0xFF383A34),
    surfaceContainerLowest = Color(0xFF0C0E09),
    surfaceContainerLow = Color(0xFF1A1C18),
    surfaceContainer = Color(0xFF1E201C),
    surfaceContainerHigh = Color(0xFF282B26),
    surfaceContainerHighest = Color(0xFF333630),
    outline = Color(0xFF8E9384),
    outlineVariant = Color(0xFF43483C),
    inverseSurface = Color(0xFFE1E4D9),
    inverseOnSurface = Color(0xFF2E312C),
    inversePrimary = Color(0xFF245C00),
    scrim = Color(0xFF000000),
)
